### ISSUE TITLE
An error is reported when starting pinpoint-collector, how to solve it？

### ISSUE THREAD

**Issue by littlesecert** [pinpoint-apm/pinpoint-kubernetes#15]
08-18 02:36:08.008 [el-Worker(11-1)] INFO  i.g.n.N.connections                      : Transport failed
io.netty.handler.codec.http2.Http2Exception: Header size exceeded max allowed size (1280)
        at io.netty.handler.codec.http2.Http2Exception.connectionError(Http2Exception.java:103) ~[netty-codec-http2-4.1.50.Final.jar!/:4.1.50.Final]
        at io.netty.handler.codec.http2.Http2CodecUtil.headerListSizeExceeded(Http2CodecUtil.java:245) ~[netty-codec-http2-4.1.50.Final.jar!/:4.1.50.Final]
        at io.netty.handler.codec.http2.DefaultHttp2FrameReader$HeadersBlockBuilder.headerSizeExceeded(DefaultHttp2FrameReader.java:694) ~[netty-codec-http2-4.1.50.Final.jar!/:4.1.50.Final]
        at io.netty.handler.codec.http2.DefaultHttp2FrameReader$HeadersBlockBuilder.addFragment(DefaultHttp2FrameReader.java:710) ~[netty-codec-http2-4.1.50.Final.jar!/:4.1.50.Final]
        at io.netty.handler.codec.http2.DefaultHttp2FrameReader$2.processFragment(DefaultHttp2FrameReader.java:481) ~[netty-codec-http2-4.1.50.Final.jar!/:4.1.50.Final]
        at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readHeadersFrame(DefaultHttp2FrameReader.java:491) ~[netty-codec-http2-4.1.50.Final.jar!/:4.1.50.Final]
        at io.netty.handler.codec.http2.DefaultHttp2FrameReader.processPayloadState(DefaultHttp2FrameReader.java:254) ~[netty-codec-http2-4.1.50.Final.jar!/:4.1.50.Final]
        at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readFrame(DefaultHttp2FrameReader.java:160) ~[netty-codec-http2-4.1.50.Final.jar!/:4.1.50.Final]
        at io.netty.handler.codec.http2.Http2InboundFrameLogger.readFrame(Http2InboundFrameLogger.java:41) ~[netty-codec-http2-4.1.50.Final.jar!/:4.1.50.Final]
        at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder.decodeFrame(DefaultHttp2ConnectionDecoder.java:174) ~[netty-codec-http2-4.1.50.Final.jar!/:4.1.50.Final]
        at io.netty.handler.codec.http2.Http2ConnectionHandler$FrameDecoder.decode(Http2ConnectionHandler.java:378) [netty-codec-http2-4.1.50.Final.jar!/:4.1.50.Final]

**Comment by jaehong-kim** [comment]
@littlesecert 
Please check the config file.

pinpoint-root.config
~~~
# agent
profiler.transport.grpc.agent.sender.headers.size.max=8K

# metadata
profiler.transport.grpc.metadata.sender.headers.size.max=8K

# stat
profiler.transport.grpc.stat.sender.headers.size.max=8K

# span
profiler.transport.grpc.span.sender.headers.size.max=8K
~~~

**Comment by littlesecert** [comment]
@jaehong-kim I did not find this file under the kuberneters pod

**Comment by thesadson** [comment]
Closing this issue since the Helm chart has been completely rewritten from scratch and now supports version 3.0.3. The new chart is more up-to-date and actively maintained.
